services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: realestate-api:latest
    ports:
      - "5236:80"
      - "7289:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
      # Comment out HTTPS for now to simplify initial setup
      # - ASPNETCORE_HTTPS_PORTS=443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 